name: Deploy example

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  deploy-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate example project sources
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: ruby generate.rb
        working-directory: ./.example

      # SSG
      - run: cp .env.example .env.local
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build

      # Deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
